homepage/urls.py

  
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
from . import views
app_name = "homepage"
urlpatterns = [
    path("index", views.index, name="index"),
    path('post/new/', PostCreateView.as_view(), name='new_post'),
    
    path('', PostListView.as_view(), name='instagram-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:pk>',views.like, name='like'),
]

instagram/urls.py
from django.contrib import admin

from django.conf.urls.static import static

from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("homepage.urls", namespace="homepage")),
    path("", include("users.urls", namespace="users")),
    path("", include("profileApp.urls", namespace="profileApp")),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)
    
if settings.DEBUG:
    urlpatterns+= static(
    settings.STATIC_URL, 
    document_root = settings.STATIC_ROOT)   

users/urls.py
from django.urls import path,include
from . import views

app_name = "users"   


urlpatterns = [
    path("/", views.register, name="register"),

]

homepage/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse
from cloudinary.models import CloudinaryField

class Post(models.Model):
    """
    Post model class to define post database table
    """
    description = models.CharField(max_length=400)
      #image field
    image = CloudinaryField('image')
    #image = models.ImageField(upload_to='uploads/')
    title = models.CharField(max_length=100, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes=models.IntegerField(null=True, default=0)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('homepage:index')
    
    @property
    def number_of_comments(self):
        return Comment.objects.filter(post=self).count()
    
class Comment(models.Model):
    """
    class to create the comment model
    """

    description = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

homepage/forms.py
from django import forms
#import comment model
from .models import Comment,Post


class CommentForm(forms.ModelForm):
    """
    Class to create a form instance of the comment model
    """
    class Meta:
        """
        Meta class to define the behavior of the class
        """
        model = Comment
        fields = ['description']


#post model form created for ui styling

homepage/views.py
from django.views.generic import CreateView
from django.shortcuts import render,redirect, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Comment
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required 
# Create your views here.
#home view

def index(request):
    context = {
        'posts':Post.objects.all()
    }
    return render(request, 'home/index.html', context)

class PostListView(ListView):
    model = Post
    template_name = 'home/index.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']

class PostDetailView(DetailView):
    model = Post
    template_name = 'gallery/post_detail.html'
    context_object_name = 'post'
    

class PostCreateView(LoginRequiredMixin, CreateView):
    """
    view class to create post
    """
    model = Post
    fields = "__all__"
    template_name = 'gallery/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

@login_required
def post(request, pk):
    """
    View to handle post model
    Args:
    Pk - Primary Key,an unique way to identify an object uniquely in relational database systems
    """
    post = Post.objects.get(pk=pk)
    user = request.user
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(author= user,description=form.cleaned_data["description"],post=post)
            comment.save()

    comments = Comment.objects.filter(post=post).order_by('-date_posted')
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }

    return self.get(self, request, pk, context)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'image', 'description']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'gallery/post_delete.html'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False

@login_required
def like(request,pk):
    post = Post.objects.get(pk=pk)
    post.likes+=1
    post.save()
    return redirect('homepage:index')


homepage/templates/gallery/post_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form method="POST" class="col-6 no-padding" style="margin-top: 9rem; text-align: center; margin-left: 16rem;">
        {% csrf_token %}
   
        <div class="card bg-dark text-white text-center">
            <img src="{{post.image.url}}" class="card-img" alt="delete">
            <div class="card-img-overlay" style="margin-top: 11rem;">
              <h5 class="card-title" style="color: green;">{{ post.description }}</h5>
                 
              <p class="card-text" style="color: red;"> <strong> Are you sure you want to delete {{post.title}}?</p>
              <p class="card-text">
                <button class="btn btn-outline-primary" type="submit">Yes</button>
                <a href="{% url 'homepage:post-detail' object.id %}" class="btn btn-outline-secondary">Cancel</a>
              </p>
            </div>
          </div>
    </form>
</div>
   
{% endblock content %}

homepage/templates/gallery/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <h3 class="white-important mb-3">
    Post
  </h3>
  <article class="media content-section">
    <div style="width: 100%; word-break: break-all;" class="hovered-tweet-comment">
      <div class="pb-2 row m-0 " style="width: 100%; margin-right: 0 !important;">
        <div style="padding-left: 0px !important;" class="col-8 no-padding d-flex align-items-center">
          <img class="rounded-circle mr-2" style="width: 20px; height: 20px;" src="{{ post.author.profile.image.url }}">
          {{ post.author }}
        </div>
        <div class="col-4 d-flex flex-row-reverse no-padding align-items-center" style="padding-right: 0 !important;">
          {% if post.author == user %}
          <div class="row">

            <div class="col">
              <a style="margin-right: 4rem;"
                        href="{% url 'homepage:post-delete' post.id %}">Trash</a>
            </div>
            <div class="col-sm-5 offset-sm-2 col-md-6 offset-md-0">
              <a 
                        href="{% url 'homepage:post-update' post.id %}">update</a>
                    
            </div>
          </div>
          {%  endif %}
        </div>
      </div>
      <div class="mb-2 " style="width: 100%;">
        <a>
          <img class="card-img-top" class="img-responsive" src="{{post.image.url}}" size="100px200">
          <p>
            {{ post.description }}
          </p>
          <small class="white-important d-flex full-width flex-row-reverse">
            {{ post.date_posted | date:"H:i l, d.m.y" }}
          </small>
        </a>
      </div>
  </article>
 
</div>

{% endblock content %}

homepage/templates/gallery/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    body {
        background-image: url(https://images.unsplash.com/photo-1633113247735-45a969eb9266?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8aW5zdGFncmFtJTIwbG9nb3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60);
        
    }
    .card {
        border: 2px solid black;
      
    }
</style>
<div class="container" style="margin-top: 5rem;">
    <div class="card">
    <div class="text-center">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
          
            <fieldset class="form-group">Create Post
               <div class="form-group">{{ form | crispy }}</div>
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="margin: 2rem;">Post</button>
            </div>
        </form>
    </div>
    
    {% endblock %}