homepage/urls.py

  
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
from . import views
app_name = "homepage"
urlpatterns = [
    path("index", views.index, name="index"),
    path('post/new/', PostCreateView.as_view(), name='new_post'),
    
    path('', PostListView.as_view(), name='instagram-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:pk>',views.like, name='like'),
]

instagram/urls.py
from django.contrib import admin

from django.conf.urls.static import static

from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("homepage.urls", namespace="homepage")),
    path("", include("users.urls", namespace="users")),
    path("", include("profileApp.urls", namespace="profileApp")),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)
    
if settings.DEBUG:
    urlpatterns+= static(
    settings.STATIC_URL, 
    document_root = settings.STATIC_ROOT)   

profileApp/urls.py
from django.urls import path
from . import views
app_name = "profileApp"
urlpatterns = [
       path('profile/', views.profile, name='profile'),
       
       path('unfollow/<to_unfollow>', views.unfollow, name='unfollow'),
       path('follow/<to_follow>', views.follow, name='follow'),
       path('search/', views.search_profile, name='search'),
       path("all_profiles/",views.all_profiles, name="all_profiles"),
       path('user_profile/<username>/', views.user_profile, name='user_profile'),
]

users/urls.py
from django.urls import path,include
from . import views

app_name = "users"   


urlpatterns = [
    path("/", views.register, name="register"),

]

homepage/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse
from cloudinary.models import CloudinaryField

class Post(models.Model):
    """
    Post model class to define post database table
    """
    description = models.CharField(max_length=400)
      #image field
    image = CloudinaryField('image')
    #image = models.ImageField(upload_to='uploads/')
    title = models.CharField(max_length=100, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes=models.IntegerField(null=True, default=0)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('homepage:index')
    
    @property
    def number_of_comments(self):
        return Comment.objects.filter(post=self).count()
    
class Comment(models.Model):
    """
    class to create the comment model
    """

    description = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

homepage/forms.py
from django import forms
#import comment model
from .models import Comment,Post


class CommentForm(forms.ModelForm):
    """
    Class to create a form instance of the comment model
    """
    class Meta:
        """
        Meta class to define the behavior of the class
        """
        model = Comment
        fields = ['description']


#post model form created for ui styling

homepage/views.py
from django.views.generic import CreateView
from django.shortcuts import render,redirect, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Comment
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required 
# Create your views here.
#home view

def index(request):
    context = {
        'posts':Post.objects.all()
    }
    return render(request, 'home/index.html', context)

class PostListView(ListView):
    model = Post
    template_name = 'home/index.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']

class PostDetailView(DetailView):
    model = Post
    template_name = 'gallery/post_detail.html'
    context_object_name = 'post'
    

class PostCreateView(LoginRequiredMixin, CreateView):
    """
    view class to create post
    """
    model = Post
    fields = "__all__"
    template_name = 'gallery/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

@login_required
def post(request, pk):
    """
    View to handle post model
    Args:
    Pk - Primary Key,an unique way to identify an object uniquely in relational database systems
    """
    post = Post.objects.get(pk=pk)
    user = request.user
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(author= user,description=form.cleaned_data["description"],post=post)
            comment.save()

    comments = Comment.objects.filter(post=post).order_by('-date_posted')
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }

    return self.get(self, request, pk, context)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'image', 'description']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'gallery/post_delete.html'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False

@login_required
def like(request,pk):
    post = Post.objects.get(pk=pk)
    post.likes+=1
    post.save()
    return redirect('homepage:index')


homepage/templates/home/footer.html
<style>
ul { 
   padding: 0px;
   text-align: center;
}
li {
   float: left;
   width: auto;
   list-style: outside none none;
}
</style>

<div class="text-center">
<center><ul>
	<li>Meta</li>
	<li>About</li>
	<li>Blog</li>
	<li>jobs</li>
	<li>API</li>
    <li>Privacy</li>
	<li>Terms</li>
	<li>Top Accounts</li>
	<li>Hashtags</li>
	<li>Location</li>
    <li>Instagram Lite</li><br>
	<li>Beauty</li>
	<li>Dance</li>
	<li>Fitness</li>
	<li>Food & Drink</li>
    <li>Home & Garden</li>
	<li>Music</li>
	<li>Visual Arts</li>

</ul></center></div>

homepage/templates/home/index.html
{% extends 'base.html' %}

{% block content %}

<!--<li>
    <a class='btn btn-default' href="/accounts/login">Login</a>
  </li>-->

  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: white;">
    <div class="container-fluid" style="background-color: white;">
      <a style="margin-left: 2rem;" class="navbar-brand" href="#">
       <!-- <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">-->
              <a class="navbar-brand" href="#" style="background-color: transparent;">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWSn3WF7L-8B3D3khyH1Rs8UYq32hbGh32rQ&usqp=CAU" alt="" style="font-size: 9vh; background-color: transparent;" class="d-inline-block align-text-top">
                
              </a>
           
    </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
          <form class="d-flex" style="margin-left: 8rem;" action="{% url 'profileApp:search' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</i>
                <span class="visually-hidden"></span>
              </div></button>
          </form>
        </ul>
        
        <span class="navbar-text">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'homepage:new_post' %}">New+</i></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'profileApp:profile'  %}">Profile</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Logout</i></a>
</li>
              <li class="nav-item">
                <p><a href=""></a></p>
              </li>
                 {% endif %}
                </li>
              </ul>
          
        </span>
      </div>
    </div>
  </nav>
  </a>
  <div class="container">
    <!-- <div class="row align-items-center">-->
      <div class="row">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" style="margin-left: 10rem; margin-bottom: 3rem;  display: inline-block;">
 <br>
     </div>
     </div>
     {% for post in posts %}
 <div style="margin: 3rem auto; width: 40rem">
  <div class="card">
    <h5 class="card-title">
      <img class="rounded-circle mr-12 article-img" style="width: 70px; height: 60px;"
      src="{{ post.author.profile.image.url }}" >
      <a class="mr-2" href="{% url 'homepage:post-detail' post.id %}">{{ post.author }}</a>
    </h5>
    <a href="{% url 'homepage:post-detail' post.id %}">
    <img
      src="{{ post.image.url }}"
      class="card-img-top"
      alt="Phone"
    /> </a><p class="mb-4">
      {{ post.description }}
  </p>
    <div class="card-body">
      
      <h6 class="card-subtitle mb-2 text-muted">
      <p class="card-text">
    
      <div class="row align-items-center">
        <div class="col">
          <a href="{% url 'homepage:like' post.pk%}">
            <i style="color: red; font-size: 16px;" class="fa fa-heart"></i>
            {{post.likes}} like(s)
        </a>
        </div>
        <div class="col">
          <a href="/post/{{post.id}}/">
            <i style=" font-size: 16px; color: blue;" class="fa fa-comment"></i>
            {{ post.number_of_comments }} comment(s)
        </a>
        </div>
        <div class="col">
          <small style="opacity: 0.8; " class="white-important d-flex full-width flex-row-reverse">
            {{ post.date_posted | date:"H:i l, d.m.y" }}
        </small>
        </div>
      </div>
     

  </div>
</div>
{% endfor %}


<div class="row">
  <div class="col-md-10">
      <div class="card mt-4 mr-2 ml-2">
          <div class="card-title text-secondary mt-2 mr-2 ml-2 ">Suggestions</div>
          {% if user.is_authenticated %}
          {% for post in posts %}
          <div class="container">
              <div class="row">
                  <div class="col-md-2 mr-3 mt-1 mb-2">
                      <img class="rounded-circle" src="{{ user.profile.image.url }}"
                           width="45px" height="45px">
                  </div>
                  <div class="col-md-6 mr-2 mt-2">
                    <span><a href="{% url 'profileApp:user_profile' user.username  %}">{{user.username}}</a></span>
                  </div>
                  <div class="col-md-4">
                  </div>
              </div>
          </div>

          {% endfor %}
          {% endif %}
<script>
    function top() {
    document.getElementById( 'top' ).scrollIntoView();    
};

function bottom() {
    document.getElementById( 'bottom' ).scrollIntoView();
    window.setTimeout( function () { top(); }, 2000 );
};

bottom();
</script>


</div>
{% endblock %}